# Export Service
# Handles exporting reasoning to different formats (Markdown, LaTeX)

import re
from datetime import datetime
from typing import Optional

from app.services import get_search_provider, get_reasoning_provider
from app.prompts import (
    get_latex_export_prompt,
    get_latex_export_system_prompt,
    get_markdown_export_prompt,
)


def convert_latex_delimiters(text: str) -> str:
    """Convert LaTeX delimiters for Google Docs compatibility."""
    # Convert \(...\) to $...$
    result = re.sub(r'\\\((.+?)\\\)', r'$\1$', text, flags=re.DOTALL)
    # Convert \[...\] to $$...$$
    result = re.sub(r'\\\[(.+?)\\\]', r'$$\1$$', result, flags=re.DOTALL)
    return result


def get_latex_preamble(problem_name: str, current_date: str, model: str = "NeuronLab AI") -> str:
    """Generate standard LaTeX preamble."""
    safe_title = problem_name.replace('#', '').replace('$', '').replace('%', '').replace('&', 'and').replace('_', ' ')
    return f"""\\documentclass[11pt,a4paper]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{amsmath,amssymb,amsthm}}
\\usepackage{{graphicx}}
\\usepackage{{hyperref}}
\\usepackage{{listings}}
\\usepackage{{xcolor}}
\\usepackage{{geometry}}
\\usepackage{{booktabs}}
\\geometry{{margin=1in}}
\\lstset{{basicstyle=\\ttfamily\\small,breaklines=true,frame=single,backgroundcolor=\\color{{gray!10}}}}
\\title{{{safe_title} -- Solution Reasoning}}
\\author{{Generated by {model}}}
\\date{{{current_date}}}
\\begin{{document}}
\\maketitle

"""


class ExportService:
    """Service for exporting reasoning to various formats."""
    
    def __init__(self, use_sonnet: bool = False):
        """
        Initialize the export service.
        
        Args:
            use_sonnet: Use Claude 4.5 Sonnet for enhanced generation
        """
        self.use_sonnet = use_sonnet
        self.search_provider = get_search_provider()
        self.reasoning_provider = get_reasoning_provider(use_perplexity=use_sonnet) if use_sonnet else None
    
    async def export_to_markdown(
        self,
        problem_name: str,
        steps: list,
        summary: str,
        web_references: str = "",
        use_ai: bool = False
    ) -> dict:
        """
        Export reasoning as formatted markdown.
        
        Args:
            problem_name: Name of the problem
            steps: List of step data with reasoning
            summary: Summary text
            web_references: Web references from search
            use_ai: Use AI to enhance formatting
        
        Returns:
            Dict with markdown content and metadata
        """
        current_date = datetime.now().strftime("%B %d, %Y")
        
        if use_ai and self.search_provider and self.search_provider.is_configured():
            try:
                steps_text = "\n\n".join([
                    f"## Step {s['step']}: {s['title']}\n{s['reasoning']}"
                    for s in steps
                ])
                
                enhance_prompt = get_markdown_export_prompt(steps_text, summary)
                enhanced = await self.search_provider.search(
                    enhance_prompt,
                    "Format mathematical content for Google Docs with LaTeX"
                )
                
                if enhanced:
                    markdown = f"# {problem_name} - Solution Reasoning\n\n"
                    markdown += f"> Generated by NeuronLab AI (Enhanced) | {current_date}\n"
                    markdown += "> Open in Google Docs with Auto-LaTeX Equations add-on for best experience\n\n"
                    markdown += convert_latex_delimiters(enhanced)
                    
                    if web_references:
                        markdown += "\n\n---\n\n## References\n\n"
                        markdown += convert_latex_delimiters(web_references)
                    
                    return {"markdown": markdown, "enhanced": True, "cached": False}
                    
            except Exception:
                pass  # Fall back to quick export
        
        # Quick export (no AI)
        markdown = f"# {problem_name} - Solution Reasoning\n\n"
        markdown += f"> Generated by NeuronLab AI | {current_date}\n"
        markdown += "> Open in Google Docs with Auto-LaTeX Equations add-on for best experience\n\n"
        
        for step in steps:
            markdown += f"## Step {step['step']}: {step['title']}\n\n"
            markdown += convert_latex_delimiters(step['reasoning']) + "\n\n"
        
        if summary:
            markdown += "---\n\n## Summary\n\n"
            markdown += convert_latex_delimiters(summary) + "\n\n"
        
        if web_references:
            markdown += "---\n\n## References\n\n"
            markdown += convert_latex_delimiters(web_references) + "\n"
        
        return {"markdown": markdown, "enhanced": False}
    
    async def export_to_latex(
        self,
        problem_name: str,
        steps: list,
        summary: str
    ) -> dict:
        """
        Export reasoning as valid LaTeX document.
        
        Args:
            problem_name: Name of the problem
            steps: List of step data with reasoning
            summary: Summary text
        
        Returns:
            Dict with LaTeX content and metadata
        """
        current_date = datetime.now().strftime("%B %d, %Y")
        
        # Build raw content
        raw_content = ""
        for step in steps:
            raw_content += f"## Step {step['step']}: {step['title']}\n\n{step['reasoning']}\n\n"
        
        if summary:
            raw_content += f"## Summary\n\n{summary}\n\n"
        
        # Try AI generation
        try:
            if self.use_sonnet and self.reasoning_provider and self.reasoning_provider.is_configured():
                latex_prompt = get_latex_export_prompt(problem_name, current_date, raw_content, use_sonnet=True)
                system_prompt = get_latex_export_system_prompt(use_sonnet=True)
                
                latex_result = await self.reasoning_provider.generate_reasoning(latex_prompt, system_prompt)
                
                if latex_result:
                    latex = self._clean_latex_result(latex_result, problem_name, current_date, "Sonnet Enhanced")
                    return {"latex": latex, "ai_generated": True, "model": "sonnet", "cached": False}
            
            elif self.search_provider and self.search_provider.is_configured():
                latex_prompt = get_latex_export_prompt(problem_name, current_date, raw_content, use_sonnet=False)
                latex_result = await self.search_provider.search(latex_prompt, "Generate valid pdfLaTeX document")
                
                if latex_result:
                    latex = self._clean_latex_result(latex_result, problem_name, current_date, "NeuronLab AI")
                    return {"latex": latex, "ai_generated": True, "cached": False}
        
        except Exception as e:
            print(f"AI LaTeX generation failed: {e}")
        
        # Fallback: Generate basic LaTeX without AI
        latex = self._generate_basic_latex(problem_name, current_date, steps, summary)
        return {"latex": latex, "ai_generated": False}
    
    def _clean_latex_result(self, latex_result: str, problem_name: str, current_date: str, model: str) -> str:
        """Clean and validate LaTeX result from AI."""
        latex = latex_result.strip()
        
        # Remove markdown wrappers
        if latex.startswith("```"):
            lines = latex.split("\n")
            latex = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
        
        # Ensure proper document structure
        if not latex.strip().startswith("\\documentclass"):
            latex = get_latex_preamble(problem_name, current_date, model) + latex
        
        if "\\end{document}" not in latex:
            latex += "\n\\end{document}\n"
        
        return latex
    
    def _generate_basic_latex(self, problem_name: str, current_date: str, steps: list, summary: str) -> str:
        """Generate basic LaTeX without AI enhancement."""
        latex = get_latex_preamble(problem_name, current_date, "NeuronLab AI")
        
        for step in steps:
            safe_title = step['title'].replace('#', '').replace('$', '').replace('%', '').replace('&', 'and').replace('_', ' ')
            latex += f"\\section{{Step {step['step']}: {safe_title}}}\n\n"
            
            content = step['reasoning']
            # Escape special characters
            for char in ['&', '%', '#', '_']:
                content = content.replace(char, '\\' + char)
            
            # Convert markdown formatting
            content = re.sub(r'\*\*([^*]+)\*\*', r'\\textbf{\1}', content)
            content = re.sub(r'\*([^*]+)\*', r'\\textit{\1}', content)
            content = re.sub(r'`([^`]+)`', r'\\texttt{\1}', content)
            
            latex += content + "\n\n"
        
        if summary:
            latex += "\\section{Summary}\n\n"
            summary_content = summary
            for char in ['&', '%', '#', '_']:
                summary_content = summary_content.replace(char, '\\' + char)
            latex += summary_content + "\n\n"
        
        latex += "\\end{document}\n"
        return latex
