"""
Notebook Converter Service - Converts reasoning data to Jupyter Notebook.

Uses nbformat to create .ipynb files with:
- Markdown cells: Mathematical theory with LaTeX
- Code cells: Python implementations (vectorized + explicit loops)

Follows sequential generation pattern like stream_full_reasoning.
"""
import json
import re
from typing import Optional

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from app.services.ai_providers import get_reasoning_provider


class NotebookConverter:
    """Converts reasoning steps to Jupyter notebook format."""
    
    def __init__(self, use_sonnet: bool = False):
        """
        Initialize converter with AI provider.
        
        Args:
            use_sonnet: If True, use Perplexity Claude 4.5 Sonnet for higher quality
        """
        self.use_sonnet = use_sonnet
        self.provider = get_reasoning_provider(use_perplexity=use_sonnet)
    
    async def convert(
        self,
        problem_title: str,
        steps: list[dict],
        summary: str = ""
    ) -> str:
        """
        Convert reasoning steps to Jupyter notebook.
        
        Args:
            problem_title: Title of the problem
            steps: List of {step, title, reasoning} dicts
            summary: Optional summary text
            
        Returns:
            JSON string of the notebook (.ipynb content)
        """
        nb = new_notebook()
        nb.metadata["kernelspec"] = {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
        
        # Title cell
        nb.cells.append(new_markdown_cell(f"# {problem_title}\n\n*Generated by NeuronLab AI*"))
        
        # Process each step sequentially with accumulated context
        previous_context = ""
        
        for step_data in steps:
            step_num = step_data.get("step", 0)
            title = step_data.get("title", f"Step {step_num}")
            reasoning = step_data.get("reasoning", "")
            
            # Step header cell
            nb.cells.append(new_markdown_cell(f"## Step {step_num}: {title}"))
            
            # Parse reasoning into interleaved markdown and code cells
            parsed_cells = self._parse_reasoning(reasoning)
            
            has_code = any(cell_type == 'code' for cell_type, _ in parsed_cells)
            
            # Add cells in their original order
            for cell_type, content in parsed_cells:
                if cell_type == 'markdown':
                    nb.cells.append(new_markdown_cell(content))
                elif cell_type == 'code':
                    nb.cells.append(new_code_cell(content))
            
            # If no code blocks found in reasoning, generate them using AI
            if not has_code:
                vectorized_code, explicit_code = await self._generate_code_cells(
                    step_num, title, reasoning, previous_context
                )
                if vectorized_code:
                    nb.cells.append(new_markdown_cell("### Vectorized Implementation (NumPy)"))
                    nb.cells.append(new_code_cell(vectorized_code))
                if explicit_code:
                    nb.cells.append(new_markdown_cell("### Explicit Loops Implementation (Pure Python)"))
                    nb.cells.append(new_code_cell(explicit_code))
            
            # Update context for next step
            previous_context += f"\n\n**Step {step_num} - {title}**: {self._summarize_step(reasoning)}"
        
        # Add summary cell
        if summary:
            nb.cells.append(new_markdown_cell(f"---\n\n## Summary\n\n{summary}"))
        
        # Validate and convert to JSON
        nbformat.validate(nb)
        return json.dumps(nb, indent=2)
    
    def _parse_reasoning(self, reasoning: str) -> list[tuple[str, str]]:
        """
        Parse reasoning content into interleaved markdown and code cells.
        
        Returns:
            List of tuples: [('markdown', content), ('code', content), ...]
            Preserves the original order of content.
        """
        cells = []
        
        # Split reasoning by code blocks while preserving order
        # Pattern matches ```python or ``` code blocks
        pattern = r'(```(?:python)?\s*\n.*?```)'
        
        # Split and keep the delimiters
        parts = re.split(pattern, reasoning, flags=re.DOTALL)
        
        for part in parts:
            if not part.strip():
                continue
                
            # Check if this part is a code block
            if part.strip().startswith('```'):
                # Extract code content (remove ``` markers)
                code_match = re.match(r'```(?:python)?\s*\n(.*?)```', part.strip(), re.DOTALL)
                if code_match:
                    code = code_match.group(1).strip()
                    if code:
                        cells.append(('code', code))
            else:
                # This is markdown content
                markdown = part.strip()
                
                # Clean up LaTeX delimiters for Jupyter compatibility
                # Convert \(...\) to $...$
                markdown = re.sub(r'\\\((.+?)\\\)', r'$\1$', markdown, flags=re.DOTALL)
                # Convert \[...\] to $$...$$
                markdown = re.sub(r'\\\[(.+?)\\\]', r'$$\1$$', markdown, flags=re.DOTALL)
                
                if markdown:
                    cells.append(('markdown', markdown))
        
        return cells
    
    def _summarize_step(self, reasoning: str) -> str:
        """Create a brief summary of a step for context passing."""
        # Take first 200 chars of reasoning (excluding code blocks)
        clean = re.sub(r'```.*?```', '', reasoning, flags=re.DOTALL)
        clean = clean.strip()[:200]
        return clean + "..." if len(clean) >= 200 else clean
    
    async def _generate_code_cells(
        self,
        step_num: int,
        title: str,
        reasoning: str,
        previous_context: str
    ) -> tuple[Optional[str], Optional[str]]:
        """
        Generate code cells using AI when no code is present in reasoning.
        
        Returns:
            tuple: (vectorized_code, explicit_loops_code)
        """
        system_prompt = """You are a Python code generator for educational Jupyter notebooks.
Generate executable Python code that demonstrates the mathematical concept.

RULES:
1. Code must be self-contained and runnable
2. Include inline comments explaining each step
3. Use simple example data that demonstrates the concept

For VECTORIZED version:
- Use basic NumPy only: np.array, np.zeros, np.ones, np.sum, np.mean, indexing
- NO advanced: np.linalg.eig, np.fft, scipy, complex matrix operations

For EXPLICIT LOOPS version:
- Pure Python only, no NumPy
- Use explicit for loops, list comprehensions
- Show every calculation step

Output ONLY the Python code, no markdown formatting."""

        context_section = ""
        if previous_context:
            context_section = f"\n\nPrevious steps context:\n{previous_context}\n"
        
        # Generate vectorized version
        vectorized_prompt = f"""Step {step_num}: {title}
{context_section}
Mathematical content to implement:
{reasoning[:1500]}

Generate a VECTORIZED Python implementation using basic NumPy (arrays, indexing, basic operations only).
Include print statements to show results."""

        vectorized_code = await self.provider.generate_reasoning(vectorized_prompt, system_prompt)
        
        # Clean the response
        vectorized_code = self._clean_code_response(vectorized_code)
        
        # Generate explicit loops version
        explicit_prompt = f"""Step {step_num}: {title}
{context_section}
Mathematical content to implement:
{reasoning[:1500]}

Generate an EXPLICIT LOOPS Python implementation using pure Python (no NumPy).
Use for loops, list comprehensions, and basic Python operations.
Include print statements to show results."""

        explicit_code = await self.provider.generate_reasoning(explicit_prompt, system_prompt)
        explicit_code = self._clean_code_response(explicit_code)
        
        return vectorized_code, explicit_code
    
    def _clean_code_response(self, response: Optional[str]) -> Optional[str]:
        """Clean AI response to extract just the code."""
        if not response:
            return None
        
        # Remove markdown code fences if present
        code = response.strip()
        if code.startswith("```"):
            lines = code.split("\n")
            # Remove first line (```python) and last line (```)
            if lines[-1].strip() == "```":
                code = "\n".join(lines[1:-1])
            else:
                code = "\n".join(lines[1:])
        
        return code.strip() if code.strip() else None
