"""add manim_animations table

Revision ID: 767f6273cdf3
Revises: 1c4666583e6e
Create Date: 2026-02-21 01:59:33.219813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767f6273cdf3'
down_revision: Union[str, Sequence[str], None] = '1c4666583e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manim_animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manim_code', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('render_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manim_animation_problem_step', 'manim_animations', ['problem_id', 'step_number'], unique=False)
    op.create_index(op.f('ix_manim_animations_id'), 'manim_animations', ['id'], unique=False)
    op.create_index(op.f('ix_manim_animations_problem_id'), 'manim_animations', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manim_animations_problem_id'), table_name='manim_animations')
    op.drop_index(op.f('ix_manim_animations_id'), table_name='manim_animations')
    op.drop_index('ix_manim_animation_problem_step', table_name='manim_animations')
    op.drop_table('manim_animations')
    # ### end Alembic commands ###
